### ISSUE TITLE
This site is down. Try again later.

### ISSUE THREAD

**Issue by enock** [sdarnell/meteor-win#3] opened 2013-04-19 11:39 UTC
Hi,

I have deployed my app, and I keep getting the "This site is down. Try again later."  error

The link is: http://enocktestapp.meteor.com/

**Comment by sdarnell** [comment] 2013-04-20 09:47
Which build of meteor were you using?
Does it run fine locally?

Here is the output from 'meteor logs enocktestapp':

```
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] NOTICE Starting application on port 15243
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] INFO STATUS starting -> running
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] WARNING     throw err;
          ^
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] WARNING module.js:340
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] WARNING Error: Cannot find module './server/server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/meteor/containers/cf21a638-66d7-e635-1439-4db80ad37f
16/bundle/main.js:1:63)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
[Sat Apr 20 2013 09:40:21 GMT+0000 (UTC)] ERROR Application crashed with code: 1
```

I guess the bundle is not quite right.

I must admit that I have only been testing locally, so there is a reasonable chance that the bundling has changed and not quite working on windows.

**Comment by sdarnell** [comment] 2013-04-21 17:59
I'm pretty sure the issue is that the directories in the bundle tar have the wrong permissions when building the archive on windows. They're missing the 'x' bit. I should have a fix soon.

**Comment by sdarnell** [comment] 2013-04-21 23:59
Fixed by https://github.com/sdarnell/meteor/commit/6582f58cbb14f932cadafc2f256f4bb3398733b0.
Please uninstall, and then reinstall the latest installer.

**Closed as completed by sdarnell** 2013-04-21 23:59 UTC

**Comment by enock** [comment] 2013-04-22 06:36
Thanks sdarnell, I have managed to get it working with the new version, thanks a lot.
