### ISSUE TITLE
Build failure 0.9.0.1

### ISSUE THREAD

**Issue by peterennis** [sdarnell/meteor-win#59] opened 2014-10-26 05:23 UTC
Log files are here:
https://github.com/peterennis/meteor/commit/859eddb0ba2a854f5bb236a900db98e2cfaad7be

build_error.log shows

C:\ae\meteor\dev_bundle\lib\node_modules\fibers\future.js:173 
 9 +                                                throw(ex); 
 10 +                                                      ^ 

The fork is up to date as of here:

https://github.com/peterennis/meteor/commit/8bfa43c6972509905fc9e4c5ae3a190dca91df63

Current state of MD instruction is here:

https://github.com/peterennis/meteor/commit/78269a5d3528bbaaae2503d50df9548e41d13e06

**Comment by peterennis** [comment] 2014-10-26 05:32
NOTE: The build error is more readable here:
https://github.com/peterennis/meteor/blob/aewin0.9.0.1/aebuild/build_error.log

and the MD here:
https://github.com/peterennis/meteor/blob/aewin0.9.0.1/aebuild/HowToBuildWindowsMeteor.md

I have "VS Express 2013 for Web" installed. Current instructions are not clear on what is the
minimum needed for the build.

**Comment by vbezruchkin** [comment] 2014-11-01 11:05
Hey guys,

I have the same error with my future.js on the same line when I run meteor update.
This is what I have now:

``` sh
C:\Users\Vasily\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86
_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
ReferenceError: warehouseDirectory is not defined
    at Object._.extend._populateWarehouseForRelease (C:\Users\Vasily\AppData\Local\.meteor\packages\
windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\warehouse.js:334:38)
    at Object._.extend.ensureReleaseExistsAndReturnManifest (C:\Users\Vasily\AppData\Local\.meteor\p
ackages\windows_meteor-tool\1.0.27\meteor-tool-os.windows.x86_32\tools\warehouse.js:115:22)
    at C:\Users\Vasily\AppData\Local\.meteor\packages\windows_meteor-tool\1.0.27\meteor-tool-os.wind
ows.x86_32\tools\main.js:870:36
```

**Comment by sdarnell** [comment] 2014-11-01 11:21
Hi Vasily, this looks like a slightly different issue (though the underlying cause may be the same).

Please could you create a separate github issue. Try to include the steps that triggered it so that I can hopefully reproduce it. For example what project did you do this on? What version was the project on? Did it have many packages? Did you update to a specific release or just run update with no args? Is that the full stack trace?

**Comment by peterennis** [comment] 2014-11-05 02:48
Using set TEMP=C:\t from #57 
Your test refers to windows:METEOR@0.9.0.1-rc3
Is the "bootstrap package as release name" in build.bat required to be this parameter?
Log file diffs here:
https://github.com/peterennis/meteor/commit/ff52b1eae2eeaffcd3fee836b8a81ee7de61ef5d
Instructions update diff here:
https://github.com/peterennis/meteor/commit/15b8ed93ca445ef2e0efa174b5528c6bd1592f4e
Build latest output results below:

```
c:\ae\meteor>mkdir C:\t
c:\ae\meteor>set TEMP=C:\t
c:\ae\meteor>scripts\windows\build.bat aewin0.9.0.1 >> build.log
The system cannot find the file specified.
c:\ae\meteor\dev_bundle\lib\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
Error: Command failed:
    at Object.Future.wait (c:\ae\meteor\dev_bundle\lib\node_modules\fibers\futur
e.js:326:15)
    at execFileSync (c:\ae\meteor\scripts\admin\build-release.js:26:8)
    at main (c:\ae\meteor\scripts\admin\build-release.js:226:3)
    - - - - -
c:\ae\meteor\tools\main.js:1296
}).run();
   ^
Error: couldn't read entire resource   expected=149390 actual=9 f=c:\ae\meteor\p
ackages\underscore\.build.underscore\os\packages\underscore.js
    at c:\ae\meteor\tools\unipackage.js:634:19
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at c:\ae\meteor\tools\unipackage.js:613:9
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at _.extend._loadUnibuildsFromPath (c:\ae\meteor\tools\unipackage.js:581:7)
    at _.extend.initFromPath (c:\ae\meteor\tools\unipackage.js:476:17)
    at _.extend._maybeGetUpToDateBuild (c:\ae\meteor\tools\catalog.js:888:14)
    at _.extend._build (c:\ae\meteor\tools\catalog.js:984:17)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\catalog.js:1176:12)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\package-loader.js:93:2
5)
    at _.extend.getPackage (c:\ae\meteor\tools\package-loader.js:55:25)
    at _.extend.getUnibuild (c:\ae\meteor\tools\package-loader.js:103:20)
    at Object.compiler.eachUsedUnibuild (c:\ae\meteor\tools\compiler.js:86:34)
    at compileUnibuild (c:\ae\meteor\tools\compiler.js:330:14)
    at c:\ae\meteor\tools\compiler.js:879:27
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at Object.compiler.compile (c:\ae\meteor\tools\compiler.js:878:5)
    at c:\ae\meteor\tools\catalog.js:992:25
    at c:\ae\meteor\tools\buildmessage.js:228:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:225:32
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.enterJob (c:\ae\meteor\tools\buildmessage.js:223:21)
    at _.extend._build (c:\ae\meteor\tools\catalog.js:988:20)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\catalog.js:1176:12)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\package-loader.js:93:2
5)
    at _.extend.getPackage (c:\ae\meteor\tools\package-loader.js:55:25)
    at _.extend.getUnibuild (c:\ae\meteor\tools\package-loader.js:103:20)
    at Object.compiler.eachUsedUnibuild (c:\ae\meteor\tools\compiler.js:86:34)
    at addToGetsUsed (c:\ae\meteor\tools\bundler.js:523:16)
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at _.extend._determineLoadOrder (c:\ae\meteor\tools\bundler.js:526:7)
    at _.extend.make (c:\ae\meteor\tools\bundler.js:449:10)
    at Object.exports.buildJsImage (c:\ae\meteor\tools\bundler.js:2089:10)
    at c:\ae\meteor\tools\uniload.js:111:25
    at c:\ae\meteor\tools\buildmessage.js:186:11
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:183:27
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:181:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.capture (c:\ae\meteor\tools\buildmessage.js:172:21)
    at Object.load (c:\ae\meteor\tools\uniload.js:92:31)
    at getLoadedPackages (c:\ae\meteor\tools\package-client.js:23:18)
    at openPackageServerConnection (c:\ae\meteor\tools\package-client.js:33:5)
    at Object.exports.updateServerPackageData (c:\ae\meteor\tools\package-client
.js:193:16)
    at _.extend._refresh (c:\ae\meteor\tools\catalog.js:189:40)
    at _.extend.refresh (c:\ae\meteor\tools\catalog.js:153:14)
    at c:\ae\meteor\tools\commands-packages.js:91:22
    at c:\ae\meteor\tools\commands-packages.js:80:11
    at c:\ae\meteor\tools\buildmessage.js:186:11
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:183:27
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:181:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.capture (c:\ae\meteor\tools\buildmessage.js:172:21)
    at exports.doOrDie (c:\ae\meteor\tools\commands-packages.js:79:31)
    at refreshOfficialCatalogOrDie (c:\ae\meteor\tools\commands-packages.js:90:3
)
    at main.registerCommand.name [as func] (c:\ae\meteor\tools\commands-packages
.js:118:3)
    at c:\ae\meteor\tools\main.js:1255:23
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
Can't read release manifest c:\ae\meteor\dist\release.json
c:\ae\meteor>
```

**Comment by sdarnell** [comment] 2014-11-05 20:38
@peterennis  I've just updated the HowToBuild instructions and the build.bat to reflect the latest.
Please sync and have a look: https://github.com/sdarnell/meteor/commit/d5fe51d6c63ac6d40ab87cd61e9de1c392286bbc

**Comment by peterennis** [comment] 2014-11-06 02:15
Latest build results here: https://github.com/peterennis/meteor/commit/daa9ad007212647ead27af3df227efd7c0e81784

```
c:\ae\meteor>scripts\windows\build.bat >> build.log
The system cannot find the file specified.

c:\ae\meteor\tools\main.js:1296
}).run();
   ^
Error: couldn't read entire resource   expected=149390 actual=9 f=c:\ae\meteor\p
ackages\underscore\.build.underscore\os\packages\underscore.js
    at c:\ae\meteor\tools\unipackage.js:634:19
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at c:\ae\meteor\tools\unipackage.js:613:9
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at _.extend._loadUnibuildsFromPath (c:\ae\meteor\tools\unipackage.js:581:7)
    at _.extend.initFromPath (c:\ae\meteor\tools\unipackage.js:476:17)
    at _.extend._maybeGetUpToDateBuild (c:\ae\meteor\tools\catalog.js:888:14)
    at _.extend._build (c:\ae\meteor\tools\catalog.js:984:17)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\catalog.js:1176:12)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\package-loader.js:93:2
5)
    at _.extend.getPackage (c:\ae\meteor\tools\package-loader.js:55:25)
    at _.extend.getUnibuild (c:\ae\meteor\tools\package-loader.js:103:20)
    at Object.compiler.eachUsedUnibuild (c:\ae\meteor\tools\compiler.js:86:34)
    at compileUnibuild (c:\ae\meteor\tools\compiler.js:330:14)
    at c:\ae\meteor\tools\compiler.js:879:27
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at Object.compiler.compile (c:\ae\meteor\tools\compiler.js:878:5)
    at c:\ae\meteor\tools\catalog.js:992:25
    at c:\ae\meteor\tools\buildmessage.js:228:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:225:32
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.enterJob (c:\ae\meteor\tools\buildmessage.js:223:21)
    at _.extend._build (c:\ae\meteor\tools\catalog.js:988:20)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\catalog.js:1176:12)
    at _.extend.getLoadPathForPackage (c:\ae\meteor\tools\package-loader.js:93:2
5)
    at _.extend.getPackage (c:\ae\meteor\tools\package-loader.js:55:25)
    at _.extend.getUnibuild (c:\ae\meteor\tools\package-loader.js:103:20)
    at Object.compiler.eachUsedUnibuild (c:\ae\meteor\tools\compiler.js:86:34)
    at addToGetsUsed (c:\ae\meteor\tools\bundler.js:523:16)
    at Array.forEach (native)
    at Function._.each._.forEach (c:\ae\meteor\dev_bundle\lib\node_modules\under
score\underscore.js:79:11)
    at _.extend._determineLoadOrder (c:\ae\meteor\tools\bundler.js:526:7)
    at _.extend.make (c:\ae\meteor\tools\bundler.js:449:10)
    at Object.exports.buildJsImage (c:\ae\meteor\tools\bundler.js:2089:10)
    at c:\ae\meteor\tools\uniload.js:111:25
    at c:\ae\meteor\tools\buildmessage.js:186:11
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:183:27
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:181:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.capture (c:\ae\meteor\tools\buildmessage.js:172:21)
    at Object.load (c:\ae\meteor\tools\uniload.js:92:31)
    at getLoadedPackages (c:\ae\meteor\tools\package-client.js:23:18)
    at openPackageServerConnection (c:\ae\meteor\tools\package-client.js:33:5)
    at Object.exports.updateServerPackageData (c:\ae\meteor\tools\package-client
.js:193:16)
    at _.extend._refresh (c:\ae\meteor\tools\catalog.js:189:40)
    at _.extend.refresh (c:\ae\meteor\tools\catalog.js:153:14)
    at c:\ae\meteor\tools\commands-packages.js:91:22
    at c:\ae\meteor\tools\commands-packages.js:80:11
    at c:\ae\meteor\tools\buildmessage.js:186:11
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:183:27
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at c:\ae\meteor\tools\buildmessage.js:181:16
    at _.extend.withValue (c:\ae\meteor\tools\fiber-helpers.js:112:14)
    at Object.capture (c:\ae\meteor\tools\buildmessage.js:172:21)
    at exports.doOrDie (c:\ae\meteor\tools\commands-packages.js:79:31)
    at refreshOfficialCatalogOrDie (c:\ae\meteor\tools\commands-packages.js:90:3
)
    at main.registerCommand.name [as func] (c:\ae\meteor\tools\commands-packages
.js:118:3)
    at c:\ae\meteor\tools\main.js:1255:23
c:\ae\meteor>
```

**Comment by sdarnell** [comment] 2014-11-06 10:01
My guess is that you have somehow got a corrupted checkout.

```
Error: couldn't read entire resource   expected=149390 actual=9 f=c:\ae\meteor\packages\underscore\.build.underscore\os\packages\underscore.js
```

I would suggest that you check what the files contain, and clean out everything but the .git directory and get a fresh checkout.

**Comment by peterennis** [comment] 2014-11-06 22:22
Looks like the branch of a fork of a fork has no food on it.
I will try again.

![capture133](https://cloud.githubusercontent.com/assets/140737/4945026/57242d30-6603-11e4-8b4f-46b7754150a5.PNG)

**Comment by peterennis** [comment] 2014-11-07 03:27
Reclone and build again while watching meteorday meetup :-)

```
C:\Users\peterennis>cd c:\ae\meteor

c:\ae\meteor>scripts\windows\build.bat >> build.log
The system cannot find the file specified.
  downloading windows:npm-node-aes-gcm at version 0.1.3 ...  done
  downloading windows:npm-bcrypt at version 0.7.7 ...  done

c:\ae\meteor>
```

**Comment by peterennis** [comment] 2014-11-07 03:30
Food is available, looking fruity!

```
c:\ae\meteor>.\meteor search sacha
Refreshing package metadata. This may take a moment.
Found the following packages:
sacha:juice  Juice wrapper package
sacha:spin   Simple spinner package for Meteor

To get more information on a specific item, use meteor show.

c:\ae\meteor>
```

**Comment by peterennis** [comment] 2014-11-07 04:05
From here:
https://github.com/sdarnell/meteor/blob/win0.9.0.1/scripts/windows/HowToBuild.md

This part is not clear to me:

If meteor-tool has been updated:

```
cd packages\meteor-tool
Update package.js to bump version number
..\..\meteor publish [--create]
```

and I interpret it like this:

https://github.com/peterennis/meteor/commit/2911ca6be2a9e3d570313cc813f15d1f883dea82

How do we know meteor-tool has been updated?
What is the version number?

This command provides info on --create:

```
c:\ae\meteor>meteor --help publish

Usage: meteor publish [--create]

Publishes a new version of a local package to the package server. Must be run
from the directory containing the package. Reads the package.js file for version

information, builds the package and sends both the package source and the built
version of the package to the package server.

This will only create one build of the package. If your package has multiple
builds for different OS architectures, it will create a build for this machine's

architecture. To publish a different build for the same version, run
publish-for-arch.

This will mark you as the only maintainer of the package. If you need to change
maintainers and other metadata about this package & package version, take a look

at the admin commands.

Pass --create to create a new package.

Options:
  --create   publish a new package


c:\ae\meteor>
```

What is the package server?
How do I make my own? (e.g. like nuget style local server)
Can you provide a checksum to verify the release?

**Comment by sdarnell** [comment] 2014-11-07 09:42
meteor-tool is basically the tools directory, and if you plan to release you will normally need to bump the version number.  Calling publish does not in itself bump the version number.
publish builds the meteor-tool package and publishes it to the meteor package server.

_What is the package server?_
The package server is a maintained by MDG and I don't believe the source is available.

_How do I make my own? (e.g. like nuget style local server)_
I emulated the package server in pre-0.9.x but I don't intend on doing it for 0.9.x. If you wanted to, you would have to reverse engineer the code that talks to it. (Or ask MDG nicely).

_Can you provide a checksum to verify the release_
Checksum of what? I'm not sure I'm on the same wavelength here.
Note that tarballs include timestamps so usually differ.

**Comment by sdarnell** [comment] 2014-11-07 09:43
Closing issue as your fork now has food on the end.

**Closed as completed by sdarnell** 2014-11-07 09:43 UTC
