### ISSUE TITLE
Changing source causes client to crash 

### ISSUE THREAD

**Issue by vinceh** [sdarnell/meteor-win#7] opened 2013-05-27 08:13 UTC
Windows 7 64-bit.

After I start my meteor server, I can go to localhost:3000 just fine.  As soon as I change a source file and refresh my client, my server crashes with 

```
=> Meteor server restarted

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at HTTPServer.Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at HTTPServer.Server.listen (net.js:986:5)
    at run (c:\Users\vinceh\Desktop\projects\leaderboard\.meteor\local\build\ser
ver\server.js:328:9)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

This error seems to mean that the meteor app isn't actually properly restarted, because the EADDRINUSE error means that the port is currently in use.  

I have to either
1.  Close my client each time I make a file change and go to localhost:3000 
2.  Restart my meteor server manually each time

Using latest Meteor_0.6.3.1-rev3.msi

**Comment by sdarnell** [comment] 2013-06-01 19:58
See also http://stackoverflow.com/questions/16866550/meteor-on-windows-server-crashes-on-code-push

**Comment by sdarnell** [comment] 2013-06-04 08:49
With my experimentation, it seems some js changes get handled OK, but updating the html triggered an error:

```
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: This socket is closed.
    at Socket._write (net.js:519:19)
    at Socket.write (net.js:511:15)
    at Socket.HttpProxy.proxyWebSocketRequest.reverseProxy.incoming.socket.on.listeners.onOutgoing (C:\Program Files (x86)\Meteor\lib\node_modules\http-proxy\lib\node-http-proxy\http-proxy.js:515:35)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
```

At that point meteor seemed to have exited, but on restarting it i get the EADDRINUSE error. So it looks like the initial exception didn't cause the child to exit.

I suspect it is the disabled keepalive code in server.js that is at least part of the issue.

Strangely, killing the second meteor invocation with Ctrl+C, and then restarting seemed to fix it. But clearly it should automatically restart cleanly.

**Comment by sdarnell** [comment] 2013-06-04 09:18
The recent comments on https://github.com/meteor/meteor/issues/513 suggest that at least the Socket.write error may be due to a buggy/old http-proxy package.

I'm also having difficulty reproducing the issue consistently. I've been doing a variety of edits to html, js client and server, and not able to get a failure. It's always the way ... sigh.

**Comment by sdarnell** [comment] 2013-06-09 21:22
I've re-enabled a heartbeat mechanism between the child and parent meteor processes - I'm not sure why it had been disabled on windows. See commit 5e9e694998b648e7c0be8b6c57a307fd1970640e

This stops the EADDRINUSE failure as the child now dies cleanly when the parent goes away.
However, it doesn't stop the initial error (http_proxy socket failure).

So things are better, but not ideal. Try the 0.6.3.1-rev4 build (uninstalling the previous version first).

**Comment by serkandurusoy** [comment] 2013-06-10 10:53
I am using rev4 now and I can confirm the issue.

It seems changes in CSS are fine, but changes in html and js crash meteor instead of expected hot code push.

On the other hand, I encounter this on linux as well.

**Comment by sdarnell** [comment] 2013-06-10 11:07
The upcoming 0.6.4 moves to a newer http_proxy which may improve the situation a bit, though looking at the latest comments on issue 513 of meteor core, it doesn't look like it has entirely fixed things.

**Comment by sdarnell** [comment] 2013-06-11 22:44
My experiments with 0.6.4 suggest that the situation is much better. I was able to modify a number of times css, html, js  (server and client) without any errors. I had multiple clients connected at the time.

Please try 0.6.4, and I suggest we open a new bug to track any further issues. I'm pretty sure the EADDRINUSE failure mode is now fixed.

**Closed as completed by sdarnell** 2013-06-11 22:44 UTC
