### ISSUE TITLE
Latest version does not install on WinXP correctly and does not cleanup after itself

### ISSUE THREAD

**Issue by hansgru** [sdarnell/meteor-win#22] opened 2013-11-05 11:54 UTC
The latest version of LaunchMeteor.exe does not install correctly on WinXP. In the last installation step, it shows something like:

```
Extracted 6101 files (101,9 MB)
Files extracted successfully

Updating PATH to include D:\Dokumente und Einstellungen\USERNAME\Anwendungsdaten\.meteor

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: no errorD:\Dokumente und Einstellungen\USERNAME\Anwendungsdaten\.meteor\tools\e42f0b78d3\lib\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Dokumente und Einstellungen\USERNAME\Anwendungsdaten\.meteor\tools\e42f0b78d3\lib\node_modules\fibers\fibers.js:17:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Please press any key to exit.
```

The buggy stuff is added to the PATH, so the user needs to manually cleanup.

regards

**Comment by sdarnell** [comment] 2013-11-05 14:28
When you say the latest version, which version are you referring to?
Do you mean the 0.6.3.3 release I did today? Given the tools hash in the traces above, I think it must be 0.6.6.3.
You can check which version got installed by looking in `%LOCALAPPDATA%\releases\latest`

Did it work for you with earlier releases, if so, which was the latest one that worked for you?

**Comment by sdarnell** [comment] 2013-11-05 19:20
Hmm, I can repro the issue (with 0.6.6.3), and there seems to be some dependency issue in the fibers.node dll.
I'm not quite sure what the issue is right now, but getting a compatible fibers.node that works with XP may be tricky going forward: https://github.com/laverdet/node-fibers/issues/140

**Comment by hansgru** [comment] 2013-11-06 09:51
> When you say the latest version, which version are you referring to? Do you mean the 0.6.3.3 release I did today? 

Since there's version number in the LaunchMeteor.exe name, nor a checksum, it's hard to say.
It's the version I downloaded a few minutes before I posted the bug.

I downloaded again - right now and it's the same exe.

> Did it work for you with earlier releases, if so, which was the latest one that worked for you?

I wasn't using the installer (Tom's releases) a while ago and it was working to a degree.

> I'm not quite sure what the issue is right now, but getting a compatible fibers.node that works with XP may be tricky going forward

Well, that's quite bad news. WinXP is alive and kicking, and for the next year most big companies won't replace their systems.

**Comment by sdarnell** [comment] 2013-11-06 22:08
I'm not writing WinXP off just yet, though it depends exactly what the issue is.

**Comment by sdarnell** [comment] 2013-11-10 00:05
OK,I managed to get a rebuilt fibers.node DLL working on XP.
For now, please could you replace the fibers.node in your %APPDATA% folder with the one from here:
https://github.com/sdarnell/meteor/raw/win0.6.6.3/scripts/windows/rebuilt-fibers/fibers.node

Please let me know how you get on, assuming it works I'll include it in the next release.

**Comment by ghost** [comment] 2014-01-15 10:57
Hi ,
     I am getting this same error. Is there a solution for this ? I tried updating the fibers.node file with the one given here and it does not work too.Same error as before .
![errormeteor](https://f.cloud.github.com/assets/6408613/1919433/dd89c6fa-7dd3-11e3-8297-2c797d6ce8ed.JPG)

**Comment by sdarnell** [comment] 2014-01-16 09:06
@dsandie I no longer have an WinXP machine to test on, and I have limited time to investigate these sorts of issues.
I would suggest that you double check the fibers.node file was replaced correctly.  The replaced file should be 137216 bytes in size.

Otherwise you might want to investigate with dumpbin http://support.microsoft.com/kb/177429 which can list imports.
I haven't tried this, but the info (loader snaps) at http://blogs.msdn.com/b/junfeng/archive/2006/11/20/debugging-loadlibrary-failures.aspx might help. But it looks like you might need a debugger attached.

A good tool I have used in the past is Dependency Walker: http://www.dependencywalker.com/

**Comment by Lucidpaper** [comment] 2014-02-10 23:23
https://github.com/sdarnell/meteor/raw/win0.6.6.3/scripts/windows/rebuilt-fibers/fibers.node worked for me.

**Comment by sdarnell** [comment] 2014-02-11 09:13
That's great @Lucidpaper thanks for confirming it works for you too.  I'm pretty sure this version is now included in the latest package (e.g. 0.7.0.1) so hopefully it should work out of the box for XP.

I'm inclined to close this issue until we get more details on why it doesn't work on some xp systems.

**Closed as completed by sdarnell** 2014-02-11 09:13 UTC
