### ISSUE TITLE
WebSocket connection error

### ISSUE THREAD

**Issue by aadamsx** [sdarnell/meteor-win#51] opened 2014-08-29 08:30 UTC
Latest code, I get the following error in Chrome console: 

"WebSocket connection to 'ws://localhost:8000/sockjs/350/yh7aanty/websocket' failed: WebSocket is closed before the connection is established.

sockjs-0.3.4.js:1300"

I'm running on port 8000.

**Comment by sdarnell** [comment] 2014-08-29 08:53
Yes, unfortunately this is due to Windows returning IPV6 addresses for localhost before IPV4, an Chrome inserting a delay between trying different IPs for the same hostname.
See https://github.com/sdarnell/meteor/issues/9 for more detail.
See https://github.com/sdarnell/meteor/issues/36 for an outstanding task of re-implementing the fix to issue 9.

In short, the problem is that Meteor only listens on the IPV4 address of localhost (127.0.0.1), Windows by default returns the IPV6 address of localhost (::1) first before 127.0.0.1, and chrome insists on delaying between making websocket connections to the different address. Nodejs also makes it really hard to listen on all endpoints of a given hostname.

The consequence is that the faye websocket implementation has a timeout before deciding to fallback to long-polling, and the delay pushes things very close.

I did implement a fix for this in a previous version, but the core meteor code was changes quite significantly in that area and requires re-implementation.

In the short term, I would suggest that you can either ignore the error (as long polling will still work - just with a little delay on startup), or switch to using 127.0.0.1:3000 instead of localhost:3000.

After 0.9 is released I'll have another look at this. But for now, I'll close this as a duplicate of issue 9 or 36.

**Closed as completed by sdarnell** 2014-08-29 08:53 UTC
