### ISSUE TITLE
No compatible build found for npm-bcrypt@0.7.

### ISSUE THREAD

**Issue by idrakimuhamad** [sdarnell/meteor-win#65] opened 2014-11-11 03:37 UTC
Hey I updated to 0.9.0.1-rc4, but this issue has started from previous rc3 version.

Whenever I tried to add a package, it will failed and I'm getting this error:

```
Refreshing package metadata. This may take a moment.
Refreshing package metadata. This may take a moment.
No compatible build found for npm-bcrypt@0.7.7
Package npm-bcrypt has no compatible build for version 0.7.7
Could not install all the requested packages.
```

I see that npm-bcrypt version in atmospherejs and they only have version 0.7.7, so I'm not sure if this a compatibility issue, or what.

**Comment by sdarnell** [comment] 2014-11-11 10:43
This is a duplicate of issue https://github.com/sdarnell/meteor/issues/58

**Closed as completed by sdarnell** 2014-11-11 10:43 UTC
