### ISSUE TITLE
Add support to pass on NTLM credentials for people behind corporate firewalls

### ISSUE THREAD

**Issue by booyaa** [sdarnell/meteor-win#20] opened 2013-09-23 08:45 UTC
Here's the error I get:

```
Downloading initial Meteor files...
Unexpected exception: System.Net.WebException: The remote server returned an err
or: (407) Proxy Authentication Required.
   at LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
   at LaunchMeteor.Program.Main(String[] args)

Please press any key to exit.
```

I tried to look for the source code to LaunchMeteor.exe, if it's available anywhere I'd be happy to provide a PR.

**Comment by sdarnell** [comment] 2013-09-23 13:29
You can find the source for LaunchMeteor.exe at: https://github.com/sdarnell/meteor/blob/win0.6.5.1/scripts/windows/LaunchMeteor.cs

It basically just creates a `new WebClient())` then calls `client.DownloadDataAsync(url)`.

My guess is that I need to specify `client.UseDefaultCredentials = true;` but if you could confirm that it gets through your proxy, that would be great.

**Comment by sdarnell** [comment] 2013-09-24 21:57
I've updated the LaunchMeteor.exe on win-install.meteor.com with this change. Please could you try it out.

**Comment by sdarnell** [comment] 2013-11-09 22:17
Assuming the change fixed it.

**Comment by philbroberts** [comment] 2013-11-20 17:50
Hi - thanks for all your work on this.  I downloaded launchmeteor.exe today (11/20/2013).  I tried to install, but got the error shown above.  I'm on a corporate network (Win7 Pro 64 bit).  I'd be glad to help troubleshoot, but I'm pretty new to this kind of and would need your guidance.

**Comment by sdarnell** [comment] 2013-11-21 09:29
@pbroberts Please could you try the new version of LaunchMeteor.exe from:
https://drive.google.com/file/d/0B4Vwungdd_-RSXFyRzlGdEt2RUk/edit?usp=sharing

This includes a bit of extra code to explicitly set the credentials on the proxy. I'm not 100% certain why the previous fix didn't work, but I've seen similar reports elsewhere and this change apparently fixes it. If it does, I'll update the main website.

**Comment by philbroberts** [comment] 2013-11-21 17:50
I ran that bin file, and here's the output:

Downloading initial Meteor files...
Unexpected exception: System.Net.WebException: The remote server returned an err
or: (407) Proxy Authentication Required. ---> SystemComponentModel.Win32Excepti
on: The function requested is not supported
     at System.Net.NTAuthentication.GetoutgoingBlob(Byte[] incomingBlob, Boolean t
hrowonError, SecurityStatus& statusCode)
     at System.Net.NTAuthentication.GetoutgoingBlob(String incomingBlob)
     at System.Net.NtlmClient.DoAuthenticate(String challenge, WebRequest webReque
st, ICredentials credentials, Boolean preAuthenticate)
     at System.Net.NtlmClient.Authenticate(String challenge, WebRequest webRequest
, ICredentials credentials)
     at System.Net.AuthenticationManager.Authenticate(String challenge, WebRequest
request, ICredentials credentials)
     at System.Net.AuthenticationState.AttemptAuthenticate(HttpWebRequest httpWebR
equest, ICredentials authlnfo)
     at System.Net.HttpNehRequest.CheckResubmitForAuth()
     at System.Net.HttpNehRequest.CheckResubmit(Exception& e)
     --- End of inner exception stack trace ---
     at LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
     at LaunchMeteor.Program.Main(String[] args)

**Comment by sdarnell** [comment] 2013-11-21 19:03
Hmm, my google goggles suggest that this is the right code, but there may be a .Net runtime issue due to the NTLM authentication requested. The issue is apparently fixed in .Net 4 - do you have this installed (or .Net 4.5?)
If you have I can re-build a version of LaunchMeteor.exe to see if that fixes it - but I'd need to get a version that will fall back to running on .Net 2 if the .Net 4 runtime is not installed.

The other possibility is to change the local security policy, though I'm not sure about this one - it may be worth a try though. See http://stackoverflow.com/a/15229403

**Comment by sdarnell** [comment] 2013-11-21 19:16
FYI There is some more info here which may offer a workaround, or it may just confirm that we need the .Net fix.
http://stackoverflow.com/questions/19158300/httpwebrequest-not-authenticating-against-proxy-server-using-kerberos

**Comment by philbroberts** [comment] 2013-11-21 21:28
I have .NET Framework 4.5 installed.  I looked at the secpol issue, but it seems it's already set as suggested (128 bit encryption is selected; NTLMv2 security is not selected).  I looked at that kerberos-ntlm link, but not sure what I could do with that info.

**Comment by sdarnell** [comment] 2013-11-23 21:54
First thing to try forcing LaunchMeteor.exe to run on the .Net 4.0 runtime. To do this, please create a file in the same directory as LaunchMeteor.exe called "LaunchMeteor.exe.config". The file should contain the following content

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup>
        <supportedRuntime version="v4.0" />
        <supportedRuntime version="v2.0.50727" />
    </startup>
</configuration>
```

You could also download this version: https://drive.google.com/file/d/0B4Vwungdd_-RS3diTFVrb3dsZ2s/edit?usp=sharing

This should cause the executable to use the .net 4 runtime, and falling back to 2.0 if necessary.

**Comment by philbroberts** [comment] 2013-11-25 15:50
Thank you!  This worked.  One detail that may be worth sharing.  I'm a beginner at all this, so when I ran the .bin file above, I renamed it to "test.bin" and that's when I got the long error message.  Today, I renamed the bin file to "LaunchMeteor.exe" and along with the config file, it worked.  Does this make a difference?  Do you want me to uninstall meteor and reinstall w/o the config file?  I'm fine with it working, but if you're curious to have the answer, I'd be glad to do that.  Just tell me how to uninstall meteor and I'll give it a go.  Thanks again.

**Comment by sdarnell** [comment] 2013-11-25 22:53
I'm pleased this sorted it out for you. There's no need to re-try after an uninstall. I just need to figure out how best to 'deliver' the fix. As you suggest, it won't be clear to many people how to properly create the config file, at least (I suspect) it only affects a small proportion of users.
Thanks for patiently trying things out, and have fun with Meteor.

**Comment by sdarnell** [comment] 2014-01-16 09:12
I considered a number of ways to deliver a 'fix'. In the end, I figured it would be better to offer an alternative method that doesn't involve LaunchMeteor.exe making the network connection. So now, there is an error message when the download fails that explains how to download the bootstrap package manually and invoke LaunchMeteor.exe with -downloaded command line option.

It's not ideal, but it is hopefully sufficient as a work-around.

**Closed as completed by sdarnell** 2014-01-16 09:12 UTC
